# Supplementary Material — Code and Derived Results

This repository contains the code and derived outputs associated with the manuscript:

**Claudio Alemán-Morillo, Natalia García-San-Martín, Richard AI Bethlehem et al., "Early deviations from normative brain morphology and cortical microstructure in schizophrenia spectrum disorders (SSD)"**  

The repository is intended to support transparency and reproducibility of the analyses reported in the article.

---

## Repository structure


---

## CODE

The `CODE` directory contains R scripts used to perform the statistical analyses and generate the results reported in the manuscript.

### `CorticalMicrostructureInSSD_Fig1_3.R`

This script runs the main set of regression analyses across multiple neuroimaging feature sets, including:

- Cortical thickness (mean and regional)
- Cortical white matter metrics
- Subcortical grey matter volumes
- White matter tracts

The script outputs:
- A multi-sheet Excel workbook containing regression results
- Optional SVG figures (brain maps or bar plots), depending on analysis settings

### `CorticalMicrostructureInSSD_Fig2.R`

This script reproduces the analyses reported in Figure 2 of the manuscript, including:

- Average fractional anisotropy (FA) vs subcortical grey matter volumes
- Subcortical grey matter volume (sGMV) vs white matter tracts
- Cortical thickness vs superficial white matter (CT ~ SWM)

The script outputs:
- A multi-sheet Excel workbook containing regression results
- Optional SVG visualizations (brain maps and bar plots)

---

## DATA

The `DATA` directory contains **derived results only**, generated by the scripts in the `CODE` directory.

- `DTI_SSD_Results_All_Figures.xlsx`  
  Multi-sheet Excel file containing regression results for analyses reported in Figures 1 ,2 and 3.

No raw or participant-level data are included in this repository.

---

## Requirements

Analyses were conducted in **R (version ≥ 4.0)**.  
The following R packages are required:

- `dplyr`
- `tidyr`
- `lmerTest`
- `ggplot2`
- `ggseg`
- `pscl`
- `grid`
- `openxlsx`

Packages can be installed using:

```r
install.packages(c(
  "dplyr", "tidyr", "lmerTest", "ggplot2", "ggseg",
  "pscl", "openxlsx"
))




## **License**

This project is licensed under the terms of the [GNU General Public License v3.0 license](LICENSE).


## **Cite**
If you use this software, please cite the following paper:
